[package]
name = 'garb'
version = '1.0.0'

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'ba5fa41f82bfe3d4e314d41c39fca77131e9f208'
subdir = 'aptos-move/framework/aptos-framework'


[addresses]
garb = "_"